### ISSUE TITLE
Failing to load resource at server root

### ISSUE THREAD

**Issue by rahuls321** [gitname/react-gh-pages#9] opened 2018-08-08 03:28 UTC
I am not able to load JSON file in the browser. 
Getting the error: 

> Failed to load /resumeData.json?_=1533629733770:1 resource: the server responded with a status of 404 ()

Please help !!!
Any help would be appreciated.
 I am attaching the screenshot of the error!!
![screenshot](https://user-images.githubusercontent.com/29652757/43814622-eee834d6-9ae8-11e8-8fc5-e6c35f414d43.jpg)

**Comment by gitname** [comment] 2018-08-08 05:39
Hi @rahuls321,

I recommend you manually visit those endpoints (i.e. those URLs) using your web browser's address bar and verify they behave the way you expect.

Assuming your app is hosted on GitHub Pages, the URLs you are using may be lacking part of the path. In other words, the file may be located at `/repository-name/resumeData.json` (and not at `/resumeData.json`).

**Comment by rahuls321** [comment] 2018-08-08 06:31
@gitname but it's working on localhost:3000 smoothly. Actually, resumeData.json file is in my public folder so, is that an issue for that error ???

**Comment by gitname** [comment] 2018-08-08 19:35
@rahuls321,

When an app hosted at `localhost:3000` or `localhost:3000/path` or `localhost:3000/deeper/path` identifies a resource as  `/resumeData.json`, it is referring to `localhost:3000/resumeData.json` (not `localhost:3000/path/resumeData.json` or `localhost:3000/deeper/path/resumeData.json`).

In other words, the `/` at the beginning of the resource identifier refers to the root folder of the server.

I think your app is working (i.e. finding the file `resumeData.json`) on `localhost:3000` because the file `resumeData.json` **is stored in the root folder of the server.**

**Similarly...**

When an app hosted at `username.github.com` or `username.github.com/path` or `username.github.com/deeper/path` identifies a resource as  `/resumeData.json`, it is referring to `username.github.com/resumeData.json` (not `username.github.com/path/resumeData.json` or `username.github.com/deeper/path/resumeData.json`).

I think your app is not working (i.e. finding the file `resumeData.json`) in this case because the file `resumeData.json` is **not stored in the root folder of the server**.

I assume, when you deploy your app to GitHub Pages, it is hosted at `username.github.com/reponame`. Assuming that is the case, when that app requests `/resumeData.json` it is still requesting `username.github.com/resumeData.json` (*not `username.github.com/reponame/resumeData.json`*).

**Fixing This**

One way to work around this is to have the app identify the resource as `/reponame/resumeData.json`. Another way is to have the app identify the resource as `./resumeData.json`.

**Comment by rahuls321** [comment] 2018-08-09 14:17
Could you please explain in detail for "fixing things" part 'coz exactly same thing happening with me as resumeData.json is located in 

>  username.github.io/resumeData.json

@gitname Thanks for helping

**Comment by gitname** [comment] 2018-08-09 23:36
@rahuls321 - I don't see anything at https://rahuls321.github.io

Will you post a link to the GitHub repository exhibiting the issue? If the repository is not publicly accessible, will you reproduce the issue in one that is publicly accessible and post a link to that instead?

**Comment by rahuls321** [comment] 2018-08-10 06:53
this is the repository [(https://github.com/rahuls321/Personal-Website)] @gitname

**Comment by gitname** [comment] 2018-08-12 18:47
@rahuls321 - Thanks for providing a link to the app exhibiting the issue.

I see the issue you reported.

1. I want to emphasize that, when your app makes a request for `/resumeData.json`, it is making a request for `https://rahuls321.github.io/resumeData.json`, **which is not where your file is stored**. Your file is stored at `https://rahuls321.github.io/Personal-Website/resumeData.json` (notice the middle part).

    I recommend you make a request for `./resumeData.json` or `/Personal-Website/resumeData.json`. However, hard-coding the latter may break your localhost deployment. To find a solution that will work in both environments, I recommend you look into the `process.env.PUBLIC_URL` environment variable described in the [create-react-app docs](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-assets-outside-of-the-module-system).

    Once you [fix the URL](https://github.com/rahuls321/Personal-Website/blob/master/src/App.js#L29) used in the request and you redeploy the app, you may find that your web browser still loads the broken version of the app. If that happens, I recommend you reload the page a few times, since you are using a [Service Worker](https://github.com/rahuls321/Personal-Website/blob/master/src/index.js#L8) in your app and that Service Worker may be caching the previous version of your app.

   If, after doing the above, the app still behaves the same way, I recommend you continue to step 2 below.

2. By default, creact-react-app enables a [Service Worker](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app). One thing the Service Worker does is cache things.

    It could be the case that the Service Worker is caching the broken version of your app (i.e. the version that does not contain the fixed URL being requested). I recommend you **unregister the Service Worker** (as shown below in the Google Chrome developer tools) and reload the page.

    ![image](https://user-images.githubusercontent.com/7143133/44005231-048c09ae-9e25-11e8-9e10-620cda763ee1.png)

**Comment by gitname** [comment] 2018-08-15 18:28
@rahuls321 - Did performing the steps in my previous comment resolve the issue for you?

---

**I will close this Issue soon** as I consider it outside of the scope of the tutorial (i.e. this repo). The tutorial covers creating a new React app via `create-react-app` and (without adding other functionality to it) deploying it to GitHub Pages.

Without the caveat I mentioned in parentheses in effect, readers could add arbitrary functionality to their apps and file an Issue here whenever their deployed apps do not behave the way they expect. It may be on me to emphasize that caveat in the tutorial (I will look into that).

In your case, you have added functionality (beyond what `create-react-app` generates) to a React app and are having issues. I was trying to help you resolve that issue as doing so seemed straightforward to me and you seemed to me to be engaged in the conversation, but I did and do consider it out of scope.

**Closed** 2018-08-16 03:11 UTC

**Comment by selcukayhan** [comment] 2019-04-10 12:57
Hi @gitname,

This issue closed much before but I want to say that I was facing same issue and changing "/resumeData.json" to "./resumeData.json"  solved my problem. 

Thank you.

**Comment by MichaelOdumosu57** [comment] 2019-08-21 17:24
thts  because ./ is a convention for OS to look for the resource in the current directory the process is in

**Comment by pissall20** [comment] 2019-10-16 07:45
Thank you so much!
