### ISSUE TITLE
my react code is deployed but page is showing blank

### ISSUE THREAD

**Issue by rahulkushwaha-in** [gitname/react-gh-pages#77] opened 2022-01-28 19:04 UTC
i am having trouble  i created m firt react project but when i uploaded to github followed every steps but when visiting the url the page is blank
![image](https://user-images.githubusercontent.com/73122192/151606280-a9e119f6-9cd4-4fad-a834-af5da3687010.png)

**Comment by shreedharhegde99** [comment] 2022-02-02 05:43
![Screenshot from 2022-02-02 11-11-39](https://user-images.githubusercontent.com/90758718/152099346-8a22521e-5437-429b-9ac7-dea7c2fcea88.png)


I visited the site and its working fine. Please change the browser and try again

**Comment by IndCore** [comment] 2022-02-09 12:39
I tried on different browsers, i also tried `Ctrl + Shift + R` to do a hard reload but it doesnt work, the website works perfectly on a localhost run.

**Comment by nakajimayoshi** [comment] 2022-12-02 09:32
same issue for me https://nakajimayoshi.github.io/businesscard/

**Comment by gitname** [comment] 2022-12-02 22:57
> same issue for me https://nakajimayoshi.github.io/businesscard/

Hi @nakajimayoshi, I visited that link in Brave and saw a non-blank page. Here's what I saw:

![image](https://user-images.githubusercontent.com/7143133/205403244-9d08f10c-d82f-42e6-b5c9-55fb80c9a194.png)

**Comment by gitname** [comment] 2022-12-02 22:58
Hi @rahulkushwaha-in , I visited https://rahulkushwaha-in.github.io/react-player/ in Brave and saw a non-blank page (same page as is shown in @shreedharhegde99 's comment -- thank you, @shreedharhegde99 ).

Closing issue due to inability to reproduce.

**Closed by gitname** 2022-12-02 22:58 UTC
